spring:
  profiles:
    include:
      - jpa
      - redis
  jackson:
    property-naming-strategy: SNAKE_CASE

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        generate_statistics: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/sample;MODE=MySQL;
      driver-class-name: org.h2.Driver
      username: sa
      password:
  sql:
    init:
      mode: embedded

logging:
  level:
    org.hibernate: debug
    org.springframework.transaction: debug