spring:
  config:
    activate:
      on-profile: test
  kafka:
    client-id: money-worker
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings:
        web-allow-others: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/sample;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;DATABASE_TO_LOWER=true;DATABASE_TO_UPPER=false;IGNORECASE=TRUE
      driver-class-name: org.h2.Driver
      username: sa
      password:
      connection-timeout: 5000
      validation-timeout: 3000
      initialization-fail-timeout: 3000
      maximum-pool-size: 30
  sql:
    init:
      mode: embedded
